EXP:
  NAME: mri
  SEED: 2022
  OUT_DIR: results/MRI

SR:
  SCALE: 2
  PATCH_SIZE_LR: 32
  BATCH_PER_GPU: 8
  MODEL: ESRGAN # ESRGAN or UPSCALER

OPT:
  MAX_ITER: 300000

OPT_CYC:
  LR_D: 0.0001
  LR_G: 0.0001
  TYPE: ADAM
  MOMENTUM: 0.9
  BETAS_D: [0.5, 0.999]
  BETAS_G: [0.5, 0.999]
  LR_MILESTONE: [100000, 180000, 240000, 280000]
  LR_DECAY: 0.5
  LOSS:
    CYC_WEIGHT: 1
    IDT_WEIGHT: 2
    GEO_WEIGHT: 1
    FREQUENCY_WEIGHT: 2
  IDT_INPUT: clean # corrupted or clean

OPT_SR:
  WARMUP: 5000
  LR_D: 0.0001
  LR_G: 0.0001
  TYPE: ADAM
  MOMENTUM: 0.9
  BETAS_D: [0.9, 0.999]
  BETAS_G: [0.9, 0.999]
  LR_MILESTONE: [10000, 18000, 24000, 28000]
  LR_DECAY: 0.9
  LOSS:
    PIXEL_WEIGHT: 0.01
    GAN_WEIGHT: 0.005

DATA:
  FOLDER: ./Dataset
  NUM_WORKERS: 0
  IMG_RANGE: 1 # for ESRGAN, set it to 1
  IMG_MEAN_SHIFT: False # for ESRGAN, set it to False
  RGB: False
